spring:
  data:
    mongodb:
      database: discount

  rabbitmq:
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWROD:guest}

messages:
  discount:
    exchange:
      name: discounts
    queue:
      name: discount
    routing-key:
      name: simple