spring:
  data:
    mongodb:
      database: discount

messages:
  discount:
    exchange:
      name: discounts
    queue:
      name: discount
    routing-key:
      name: simple
    test:
      key: val