apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce 
  volumeName: mongo-pvc
  resources:
    requests:
      storage: 1Gi